# Generated by Django 4.0.5 on 2022-08-31 08:32

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to=shop.models.shop_products_images_path),
        ),
    ]
